name: {{ cookiecutter.conda_env_name }}
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python={{ cookiecutter.python_version }}
  - pip

  # Jupyter
  - jupyter
  - notebook
  - ipykernel
  - jupyterlab

  # Data Manipulation and Analysis
  - numpy
  - pandas
  - scipy
  - statsmodels

  # Machine Learning
  - scikit-learn

  # Visualization
  - matplotlib
  - seaborn

  # Utilities
  - tqdm

  # Testing
  - pytest