name: {{ cookiecutter.conda_env_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - jupyter
  - ipykernel
  - notebook

